//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceHogarApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Calificaciones
    {
        public int ID { get; set; }
        public Nullable<int> CALIFICACION { get; set; }
        public Nullable<int> IDUSUARIO { get; set; }
    
        public virtual TB_Profesionales TB_Profesionales { get; set; }
    }
}
