//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceHogarApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TB_Profesionales
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_Profesionales()
        {
            this.TB_Calificaciones = new HashSet<TB_Calificaciones>();
        }

        public int IDUSUARIO { get; set; }
        public string TIPO { get; set; }

        [Required(ErrorMessage = "Necesita ingresar su nombre")]
        [StringLength(12, ErrorMessage = "Nombre demasiado largo")]
        public string NOMBRE { get; set; }

        [Required(ErrorMessage = "Necesita ingresar su apellido")]
        [StringLength(12, ErrorMessage = "Apellido demasiado largo")]
        public string APELLIDO { get; set; }

        [Required(ErrorMessage = "Necesita ingresar su DNI")]
        [RegularExpression("([0-9]+)", ErrorMessage = "Ingese solo números")]
        [StringLength(8, MinimumLength = 8, ErrorMessage = "Ingrese 8 dígitos")]
        public string DNI { get; set; }

        [Required(ErrorMessage = "Necesita ingresar un usuario")]
        [StringLength(8, ErrorMessage = "Máximo 8 caracteres")]
        public string USUARIO { get; set; }

        [Required(ErrorMessage = "Necesita ingresar una clave")]
        [StringLength(8, MinimumLength = 8, ErrorMessage = "Ingrese una clase de 8 dígitos")]
        public string CLAVE { get; set; }

        [Required(ErrorMessage = "Elija un sexo")]
        public string SEXO { get; set; }

        [Required(ErrorMessage = "Elija su fecha de nacimiento")]
        [Display(Name = "FECHA DE NACIMIENTO")]
        public Nullable<System.DateTime> FECHANAC { get; set; }

        [Required(ErrorMessage = "Ingrese su Distrito")]
        public string DISTRITO { get; set; }

        [Required(ErrorMessage = "Escoja su especialidad")]
        public string ESPECIALIDAD { get; set; }

        [Required(ErrorMessage = "Ingrese una descripción")]
        [StringLength(100, ErrorMessage = "Máximo 100 caracteres")]
        public string DESCRIPCIÓN { get; set; }
        public Nullable<int> PROMEDIOCAL { get; set; }

        public string CV { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_Calificaciones> TB_Calificaciones { get; set; }
    }
}
