//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceHogarApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Usuarios
    {
        public int IDUSUARIO { get; set; }
        public string TIPO { get; set; }
        public string NOMBRE { get; set; }
        public string APELLIDO { get; set; }
        public string DNI { get; set; }
        public string USUARIO { get; set; }
        public string CLAVE { get; set; }
        public string SEXO { get; set; }
        public Nullable<System.DateTime> FECHANAC { get; set; }
        public string DISTRITO { get; set; }
    }
}
